apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  labels:
    app: springboot-app
    environment: production # You can change this to staging, dev, etc.
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # Example for AWS NLB, adjust as needed
spec:
  type: LoadBalancer
  ports:
    - name: http # Added a name for the port
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: springboot-app
